### ISSUE TITLE
getting told using api keys in console every login

### ISSUE THREAD

**Issue by Kaisarion** [chriscn/hypixeljs#22]
i see no setting parameters to disable this. any suggestions?

**Comment by chriscn** [comment]
This will be due to the following line:
https://github.com/chriscn/hypixeljs/blob/4a6c29e201b0985d7c91a506c0b0d0a8f486f544/lib/api.js#L44

Would suggest migrating to [hypixel.ts](https://github.com/hypixelts).

**Comment by Kaisarion** [comment]
I do not see it necessary to keep in the code regardless. Why do you have it in the first place?

**Comment by chriscn** [comment]
`v1.4.1` @ [https://www.npmjs.com/package/hypixeljs](https://www.npmjs.com/package/hypixeljs) should fix this for you

**Comment by Kaisarion** [comment]
cheers
